export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_PENDING = 'SIGNUP_PENDING';

export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SETUP_USER = 'SETUP_USER';
