const actionTypes = {
  SINGLE_ARTICLE_PENDING: 'SINGLE_ARTICLE_PENDING',
  SINGLE_ARTICLE_SUCCESS: 'SINGLE_ARTICLE_SUCCESS',
  SINGLE_ARTICLE_FAILED: 'SINGLE_ARTICLE_FAILED',
  REQUIRE_LOGIN: 'REQUIRE_LOGIN'
};

export default actionTypes;
