const actionTypes = {
  SINGLE_ARTICLE_PENDING: 'SINGLE_ARTICLE_PENDING',
  SINGLE_ARTICLE_SUCCESS: 'SINGLE_ARTICLE_SUCCESS',
  SINGLE_ARTICLE_FAILED: 'SINGLE_ARTICLE_FAILED'
};

export default actionTypes;
