const actionTypes = {
  PASSWORD_RESET_PENDING: 'PASSWORD_RESET_PENDING',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED'
};

export default actionTypes;
